name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test --coverage

      - name: List coverage directory
        run: ls -R coverage/
        
      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@3
        with:
          name: coverage-report
          path: coverage/*
